/**
 * @file atmega328.h
 * @author your name (you@domain.com)
 * @brief 
 * @version 0.1
 * @date 2023-06-23
 * 
 * @copyright Copyright (c) 2023
 * 
 */


#ifndef ATMEGE_328_H__
#define ATMEGE_328_H__


#include <stdint.h>

#define UDR0    (*( uint8_t *)    (0xC6)) 
#define UBRR0H  (*( uint8_t *)    (0xC5)) 
#define UBRR0L  (*( uint8_t *)    (0xC4)) 
#define UCSR0C  (*( uint8_t *)    (0xC2)) 
#define UCSR0B  (*( uint8_t *)    (0xC1)) 
#define UCSR0A  (*( uint8_t *)    (0xC0)) 
#define TWAMR   (*( uint8_t *)    (0xBD)) 
#define TWCR    (*( uint8_t *)    (0xBC)) 
#define TWDR    (*( uint8_t *)    (0xBB)) 
#define TWAR    (*( uint8_t *)    (0xBA)) 
#define TWSR    (*( uint8_t *)    (0xB9)) 
#define TWBR    (*( uint8_t *)    (0xB8)) 
#define ASSR    (*( uint8_t *)    (0xB6)) 
#define OCR2B   (*( uint8_t *)    (0xB4)) 
#define OCR2A   (*( uint8_t *)    (0xB3)) 
#define TCNT2   (*( uint8_t *)    (0xB2)) 
#define TCCR2B  (*( uint8_t *)    (0xB1)) 
#define TCCR2A  (*( uint8_t *)    (0xB0)) 
#define OCR1BH  (*( uint8_t *)    (0x8B)) 
#define OCR1BL  (*( uint8_t *)    (0x8A)) 
#define OCR1AH  (*( uint8_t *)    (0x89)) 
#define OCR1AL  (*( uint8_t *)    (0x88)) 
#define ICR1H   (*( uint8_t *)    (0x87)) 
#define ICR1L   (*( uint8_t *)    (0x86)) 
#define TCNT1H  (*( uint8_t *)    (0x85)) 
#define TCNT1L  (*( uint8_t *)    (0x84)) 
#define TCCR1C  (*( uint8_t *)    (0x82)) 
#define TCCR1B  (*( uint8_t *)    (0x81)) 
#define TCCR1A  (*( uint8_t *)    (0x80)) 
#define DIDR1   (*( uint8_t *)    (0x7F)) 
#define DIDR0   (*( uint8_t *)    (0x7E)) 
#define ADMUX   (*( uint8_t *)    (0x7C)) 
#define ADCSRB  (*( uint8_t *)    (0x7B)) 
#define ADCSRA  (*( uint8_t *)    (0x7A)) 
#define ADCH    (*( uint8_t *)    (0x79)) 
#define ADCL    (*( uint8_t *)    (0x78)) 
#define TIMSK2  (*( uint8_t *)    (0x70)) 
#define TIMSK1  (*( uint8_t *)    (0x6F)) 
#define TIMSK0  (*( uint8_t *)    (0x6E)) 
#define PCMSK2  (*( uint8_t *)    (0x6D)) 
#define PCMSK1  (*( uint8_t *)    (0x6C)) 
#define PCMSK0  (*( uint8_t *)    (0x6B)) 
#define EICRA   (*( uint8_t *)    (0x69)) 
#define PCICR   (*( uint8_t *)    (0x68)) 
#define OSCCAL  (*( uint8_t *)    (0x66)) 
#define PRR     (*( uint8_t *)    (0x64)) 
#define CLKPR   (*( uint8_t *)    (0x61)) 
#define WDTCSR  (*( uint8_t *)    (0x60)) 
#define SREG    (*( uint8_t *)    (0x5F)) 
#define SPH     (*( uint8_t *)    (0x5E)) 
#define SPL     (*( uint8_t *)    (0x5D)) 
#define SPMCSR  (*( uint8_t *)    (0x57)) 
#define MCUCR   (*( uint8_t *)    (0x55)) 
#define MCUSR   (*( uint8_t *)    (0x54)) 
#define SMCR    (*( uint8_t *)    (0x53)) 
#define ACSR    (*( uint8_t *)    (0x50)) 
#define SPDR    (*( uint8_t *)    (0x4E)) 
#define SPSR    (*( uint8_t *)    (0x4D)) 
#define SPCR    (*( uint8_t *)    (0x4C)) 
#define GPIOR2  (*( uint8_t *)    (0x4B)) 
#define GPIOR1  (*( uint8_t *)    (0x4A)) 
#define OCR0B   (*( uint8_t *)    (0x48)) 
#define OCR0A   (*( uint8_t *)    (0x47)) 
#define TCNT0   (*( uint8_t *)    (0x46)) 
#define TCCR0B  (*( uint8_t *)    (0x45)) 
#define TCCR0A  (*( uint8_t *)    (0x44)) 
#define GTCCR   (*( uint8_t *)    (0x43)) 
#define EEARH   (*( uint8_t *)    (0x42)) 
#define EEARL   (*( uint8_t *)    (0x41)) 
#define EEDR    (*( uint8_t *)    (0x40)) 
#define EECR    (*( uint8_t *)    (0x3F)) 
#define GPIOR0  (*( uint8_t *)    (0x3E)) 
#define EIMSK   (*( uint8_t *)    (0x3D)) 
#define EIFR    (*( uint8_t *)    (0x3C)) 
#define PCIFR   (*( uint8_t *)    (0x3B)) 
#define TIFR2   (*( uint8_t *)    (0x37)) 
#define TIFR1   (*( uint8_t *)    (0x36)) 
#define TIFR0   (*( uint8_t *)    (0x35)) 
#define PORTD   (*( uint8_t *)    (0x2B)) 
#define DDRD    (*( uint8_t *)    (0x2A)) 
#define PIND    (*( uint8_t *)    (0x29)) 
#define PORTC   (*( uint8_t *)    (0x28)) 
#define DDRC    (*( uint8_t *)    (0x27)) 
#define PINC    (*( uint8_t *)    (0x26)) 
#define PORTB   (*( uint8_t *)    (0x25)) 
#define DDRB    (*( uint8_t *)    (0x24)) 
#define PINB    (*( uint8_t *)    (0x23)) 


typedef struct 
{
    /* data */
} GPIO_TypeDef;









#define UDR0_USART (uint8_t)( 1UL << 7) 
#define UBRR0H_USART  (uint8_t)(1UL << 3) 
#define UBRR0L_USART (uint8_t)( 1UL << 7) 
#define UCSR0C_UMSEL01 (uint8_t)( 1UL << 7) 
#define UCSR0C_UMSEL00 (uint8_t)( 1UL << 6) 
#define UCSR0C_UPM01  (uint8_t)(1UL << 5) 
#define UCSR0C_UPM00  (uint8_t)(1UL << 4) 
#define UCSR0C_USBS0  (uint8_t)(1UL << 3) 
#define UCSR0C_UCSZ01 (uint8_t)(1UL << 2) 
#define UCSR0C_UCSZ00 (uint8_t)(1UL << 1) 
#define UCSR0C_UCPOL0  (uint8_t)(1UL << 0) 
#define UCSR0B_RXCIE0 (uint8_t)( 1UL << 7) 
#define UCSR0B_TXCIE0 (uint8_t)( 1UL << 6) 
#define UCSR0B_UDRIE0  (uint8_t)(1UL << 5) 
#define UCSR0B_RXEN0  (uint8_t)(1UL << 4) 
#define UCSR0B_TXEN0  (uint8_t)(1UL << 3) 
#define UCSR0B_UCSZ02  (uint8_t)(1UL << 2) 
#define UCSR0B_RXB80  (uint8_t)(1UL << 1) 
#define UCSR0B_TXB80  (uint8_t)(1UL << 0) 
#define UCSR0A_RXC0 (uint8_t)( 1UL << 7) 
#define UCSR0A_TXC0 (uint8_t)( 1UL << 6) 
#define UCSR0A_UDRE0  (uint8_t)(1UL << 5) 
#define UCSR0A_FE0  (uint8_t)(1UL << 4) 
#define UCSR0A_DOR0  (uint8_t)(1UL << 3) 
#define UCSR0A_UPE0  (uint8_t)(1UL << 2) 
#define UCSR0A_U2X0  (uint8_t)(1UL << 1) 
#define UCSR0A_MPCM0  (uint8_t)(1UL << 0) 
#define TWAMR_TWAM6 (uint8_t)( 1UL << 7) 
#define TWAMR_TWAM5 (uint8_t)( 1UL << 6) 
#define TWAMR_TWAM4  (uint8_t)(1UL << 5) 
#define TWAMR_TWAM3  (uint8_t)(1UL << 4) 
#define TWAMR_TWAM2  (uint8_t)(1UL << 3) 
#define TWAMR_TWAM1  (uint8_t)(1UL << 2) 
#define TWAMR_TWAM0  (uint8_t)(1UL << 1) 
// #define TWAMR_�  (uint8_t)(1UL << 0) 
#define TWCR_TWINT (uint8_t)( 1UL << 7) 
#define TWCR_TWEA (uint8_t)( 1UL << 6) 
#define TWCR_TWSTA  (uint8_t)(1UL << 5) 
#define TWCR_TWSTO  (uint8_t)(1UL << 4) 
#define TWCR_TWWC  (uint8_t)(1UL << 3) 
#define TWCR_TWEN  (uint8_t)(1UL << 2) 
#define TWDR_2_wire (uint8_t)( 1UL << 7) 
#define TWAR_TWA6 (uint8_t)( 1UL << 7) 
#define TWAR_TWA5 (uint8_t)( 1UL << 6) 
#define TWAR_TWA4  (uint8_t)(1UL << 5) 
#define TWAR_TWA3  (uint8_t)(1UL << 4) 
#define TWAR_TWA2  (uint8_t)(1UL << 3) 
#define TWAR_TWA1  (uint8_t)(1UL << 2) 
#define TWAR_TWA0  (uint8_t)(1UL << 1) 
#define TWAR_TWGCE  (uint8_t)(1UL << 0) 
#define TWSR_TWS7 (uint8_t)( 1UL << 7) 
#define TWSR_TWS6 (uint8_t)( 1UL << 6) 
#define TWSR_TWS5  (uint8_t)(1UL << 5) 
#define TWSR_TWS4  (uint8_t)(1UL << 4) 
#define TWSR_TWS3  (uint8_t)(1UL << 3) 
#define TWSR_TWPS1  (uint8_t)(1UL << 1) 
#define TWSR_TWPS0  (uint8_t)(1UL << 0) 
#define TWBR_2_wire (uint8_t)( 1UL << 7) 
#define ASSR_EXCLK (uint8_t)( 1UL << 6) 
#define ASSR_AS2  (uint8_t)(1UL << 5) 
#define ASSR_TCN2UB  (uint8_t)(1UL << 4) 
#define ASSR_OCR2AUB  (uint8_t)(1UL << 3) 
#define ASSR_OCR2BUB  (uint8_t)(1UL << 2) 
#define ASSR_TCR2AUB  (uint8_t)(1UL << 1) 
#define ASSR_TCR2BUB  (uint8_t)(1UL << 0) 
#define OCR2B_Timer (uint8_t)( 1UL << 7) 
#define OCR2A_Timer (uint8_t)( 1UL << 7) 
#define TCNT2_Timer (uint8_t)( 1UL << 7) 
#define TCCR2B_FOC2A (uint8_t)( 1UL << 7) 
#define TCCR2B_FOC2B (uint8_t)( 1UL << 6) 
#define TCCR2B_WGM22  (uint8_t)(1UL << 3) 
#define TCCR2B_CS22  (uint8_t)(1UL << 2) 
#define TCCR2B_CS21  (uint8_t)(1UL << 1) 
#define TCCR2B_CS20  (uint8_t)(1UL << 0) 
#define TCCR2A_COM2A1 (uint8_t)( 1UL << 7) 
#define TCCR2A_COM2A0 (uint8_t)( 1UL << 6) 
#define TCCR2A_COM2B1  (uint8_t)(1UL << 5) 
#define TCCR2A_COM2B0  (uint8_t)(1UL << 4) 
#define TCCR2A_WGM21  (uint8_t)(1UL << 1) 
#define TCCR2A_WGM20  (uint8_t)(1UL << 0) 
#define OCR1BH_Timer (uint8_t)( 1UL << 7) 
#define OCR1BL_Timer (uint8_t)( 1UL << 7) 
#define OCR1AH_Timer (uint8_t)( 1UL << 7) 
#define OCR1AL_Timer (uint8_t)( 1UL << 7) 
#define ICR1H_Timer (uint8_t)( 1UL << 7) 
#define ICR1L_Timer (uint8_t)( 1UL << 7) 
#define TCNT1H_Timer (uint8_t)( 1UL << 7) 
#define TCNT1L_Timer (uint8_t)( 1UL << 7) 
#define TCCR1C_FOC1A (uint8_t)( 1UL << 7) 
#define TCCR1C_FOC1B (uint8_t)( 1UL << 6) 
#define TCCR1B_ICNC1 (uint8_t)( 1UL << 7) 
#define TCCR1B_ICES1 (uint8_t)( 1UL << 6) 
#define TCCR1B_WGM13  (uint8_t)(1UL << 4) 
#define TCCR1B_WGM12  (uint8_t)(1UL << 3) 
#define TCCR1B_CS12  (uint8_t)(1UL << 2) 
#define TCCR1B_CS11  (uint8_t)(1UL << 1) 
#define TCCR1B_CS10  (uint8_t)(1UL << 0) 
#define TCCR1A_COM1A1 (uint8_t)( 1UL << 7) 
#define TCCR1A_COM1A0 (uint8_t)( 1UL << 6) 
#define TCCR1A_COM1B1  (uint8_t)(1UL << 5) 
#define TCCR1A_COM1B0  (uint8_t)(1UL << 4) 
#define TCCR1A_WGM11  (uint8_t)(1UL << 1) 
#define TCCR1A_WGM10  (uint8_t)(1UL << 0) 
#define DIDR1_AIN1D  (uint8_t)(1UL << 1) 
#define DIDR1_AIN0D  (uint8_t)(1UL << 0) 
#define DIDR0_ADC5D  (uint8_t)(1UL << 5) 
#define DIDR0_ADC4D  (uint8_t)(1UL << 4) 
#define DIDR0_ADC3D  (uint8_t)(1UL << 3) 
#define DIDR0_ADC2D  (uint8_t)(1UL << 2) 
#define DIDR0_ADC1D  (uint8_t)(1UL << 1) 
#define DIDR0_ADC0D  (uint8_t)(1UL << 0) 
#define ADMUX_REFS1 (uint8_t)( 1UL << 7) 
#define ADMUX_REFS0 (uint8_t)( 1UL << 6) 
#define ADMUX_ADLAR  (uint8_t)(1UL << 5) 
#define ADMUX_MUX3  (uint8_t)(1UL << 3) 
#define ADMUX_MUX2  (uint8_t)(1UL << 2) 
#define ADMUX_MUX1  (uint8_t)(1UL << 1) 
#define ADMUX_MUX0  (uint8_t)(1UL << 0) 
#define ADCSRB_ACME (uint8_t)( 1UL << 6) 
#define ADCSRB_ADTS2  (uint8_t)(1UL << 2) 
#define ADCSRB_ADTS1  (uint8_t)(1UL << 1) 
#define ADCSRB_ADTS0  (uint8_t)(1UL << 0) 
#define ADCSRA_ADEN (uint8_t)( 1UL << 7) 
#define ADCSRA_ADSC (uint8_t)( 1UL << 6) 
#define ADCSRA_ADATE  (uint8_t)(1UL << 5) 
#define ADCSRA_ADIF  (uint8_t)(1UL << 4) 
#define ADCSRA_ADIE  (uint8_t)(1UL << 3) 
#define ADCSRA_ADPS2  (uint8_t)(1UL << 2) 
#define ADCSRA_ADPS1  (uint8_t)(1UL << 1) 
#define ADCSRA_ADPS0  (uint8_t)(1UL << 0) 
#define ADCH_ADC (uint8_t)( 1UL << 7) 
#define ADCL_ADC (uint8_t)( 1UL << 7) 
#define TIMSK2_OCIE2B  (uint8_t)(1UL << 2) 
#define TIMSK2_OCIE2A  (uint8_t)(1UL << 1) 
#define TIMSK2_TOIE2  (uint8_t)(1UL << 0) 
#define TIMSK1_ICIE1  (uint8_t)(1UL << 5) 
#define TIMSK1_OCIE1B  (uint8_t)(1UL << 2) 
#define TIMSK1_OCIE1A  (uint8_t)(1UL << 1) 
#define TIMSK1_TOIE1  (uint8_t)(1UL << 0) 
#define TIMSK0_OCIE0B  (uint8_t)(1UL << 2) 
#define TIMSK0_OCIE0A  (uint8_t)(1UL << 1) 
#define TIMSK0_TOIE0  (uint8_t)(1UL << 0) 
#define PCMSK2_PCINT23 (uint8_t)( 1UL << 7) 
#define PCMSK2_PCINT22 (uint8_t)( 1UL << 6) 
#define PCMSK2_PCINT21  (uint8_t)(1UL << 5) 
#define PCMSK2_PCINT20  (uint8_t)(1UL << 4) 
#define PCMSK2_PCINT19  (uint8_t)(1UL << 3) 
#define PCMSK2_PCINT18  (uint8_t)(1UL << 2) 
#define PCMSK2_PCINT17  (uint8_t)(1UL << 1) 
#define PCMSK2_PCINT16  (uint8_t)(1UL << 0) 
#define PCMSK1_PCINT14 (uint8_t)( 1UL << 6) 
#define PCMSK1_PCINT13  (uint8_t)(1UL << 5) 
#define PCMSK1_PCINT12  (uint8_t)(1UL << 4) 
#define PCMSK1_PCINT11  (uint8_t)(1UL << 3) 
#define PCMSK1_PCINT10  (uint8_t)(1UL << 2) 
#define PCMSK1_PCINT9  (uint8_t)(1UL << 1) 
#define PCMSK1_PCINT8  (uint8_t)(1UL << 0) 
#define PCMSK0_PCINT7 (uint8_t)( 1UL << 7) 
#define PCMSK0_PCINT6 (uint8_t)( 1UL << 6) 
#define PCMSK0_PCINT5  (uint8_t)(1UL << 5) 
#define PCMSK0_PCINT4  (uint8_t)(1UL << 4) 
#define PCMSK0_PCINT3  (uint8_t)(1UL << 3) 
#define PCMSK0_PCINT2  (uint8_t)(1UL << 2) 
#define PCMSK0_PCINT1  (uint8_t)(1UL << 1) 
#define PCMSK0_PCINT0  (uint8_t)(1UL << 0) 
#define EICRA_ISC11  (uint8_t)(1UL << 3) 
#define EICRA_ISC10  (uint8_t)(1UL << 2) 
#define EICRA_ISC01  (uint8_t)(1UL << 1) 
#define EICRA_ISC00  (uint8_t)(1UL << 0) 
#define PCICR_PCIE2  (uint8_t)(1UL << 2) 
#define PCICR_PCIE1  (uint8_t)(1UL << 1) 
#define PCICR_PCIE0  (uint8_t)(1UL << 0) 
#define OSCCAL_Oscillator (uint8_t)( 1UL << 7) 
#define PRR_PRTWI (uint8_t)( 1UL << 7) 
#define PRR_PRTIM2 (uint8_t)( 1UL << 6) 
#define PRR_PRTIM0  (uint8_t)(1UL << 5) 
#define PRR_PRTIM1  (uint8_t)(1UL << 3) 
#define PRR_PRSPI  (uint8_t)(1UL << 2) 
#define PRR_PRUSAR0  (uint8_t)(1UL << 1) 
#define PRR_PRADC  (uint8_t)(1UL << 0) 
#define CLKPR_CLKPCE (uint8_t)( 1UL << 7) 
#define CLKPR_CLKPS3  (uint8_t)(1UL << 3) 
#define CLKPR_CLKPS2  (uint8_t)(1UL << 2) 
#define CLKPR_CLKPS1  (uint8_t)(1UL << 1) 
#define CLKPR_CLKPS0  (uint8_t)(1UL << 0) 
#define WDTCSR_WDIF (uint8_t)( 1UL << 7) 
#define WDTCSR_WDIE (uint8_t)( 1UL << 6) 
#define WDTCSR_WDP3  (uint8_t)(1UL << 5) 
#define WDTCSR_WDCE  (uint8_t)(1UL << 4) 
#define WDTCSR_WDE  (uint8_t)(1UL << 3) 
#define WDTCSR_WDP2  (uint8_t)(1UL << 2) 
#define WDTCSR_WDP1  (uint8_t)(1UL << 1) 
#define WDTCSR_WDP0  (uint8_t)(1UL << 0) 
#define SREG_I (uint8_t)( 1UL << 7) 
#define SREG_T (uint8_t)( 1UL << 6) 
#define SREG_H  (uint8_t)(1UL << 5) 
#define SREG_S  (uint8_t)(1UL << 4) 
#define SREG_V  (uint8_t)(1UL << 3) 
#define SREG_N  (uint8_t)(1UL << 2) 
#define SREG_Z  (uint8_t)(1UL << 1) 
#define SREG_C  (uint8_t)(1UL << 0) 
#define SPH_SP10  (uint8_t)(1UL << 2) 
#define SPH_SP9  (uint8_t)(1UL << 1) 
#define SPH_SP8  (uint8_t)(1UL << 0) 
#define SPL_SP7 (uint8_t)( 1UL << 7) 
#define SPL_SP6 (uint8_t)( 1UL << 6) 
#define SPL_SP5  (uint8_t)(1UL << 5) 
#define SPL_SP4  (uint8_t)(1UL << 4) 
#define SPL_SP3  (uint8_t)(1UL << 3) 
#define SPL_SP2  (uint8_t)(1UL << 2) 
#define SPL_SP1  (uint8_t)(1UL << 1) 
#define SPL_SP0  (uint8_t)(1UL << 0) 
#define SPMCSR_SPMIE (uint8_t)( 1UL << 7) 
#define SPMCSR_RWWSB (uint8_t)( 1UL << 6) 
#define SPMCSR_RWWSRE  (uint8_t)(1UL << 4) 
#define SPMCSR_BLBSET  (uint8_t)(1UL << 3) 
#define SPMCSR_PGWRT  (uint8_t)(1UL << 2) 
#define SPMCSR_PGERS  (uint8_t)(1UL << 1) 
#define SPMCSR_SELFPRGN  (uint8_t)(1UL << 0) 
#define MCUCR_BODS (uint8_t)( 1UL << 6) 
#define MCUCR_BODSE  (uint8_t)(1UL << 5) 
#define MCUCR_PUD  (uint8_t)(1UL << 4) 
#define MCUCR_IVSEL  (uint8_t)(1UL << 1) 
#define MCUCR_IVCE  (uint8_t)(1UL << 0) 
#define MCUSR_WDRF  (uint8_t)(1UL << 3) 
#define MCUSR_BORF  (uint8_t)(1UL << 2) 
#define MCUSR_EXTRF  (uint8_t)(1UL << 1) 
#define MCUSR_PORF  (uint8_t)(1UL << 0) 
#define SMCR_SM2  (uint8_t)(1UL << 3) 
#define SMCR_SM1  (uint8_t)(1UL << 2) 
#define SMCR_SM0  (uint8_t)(1UL << 1) 
#define SMCR_SE  (uint8_t)(1UL << 0) 
#define ACSR_ACD (uint8_t)( 1UL << 7) 
#define ACSR_ACBG (uint8_t)( 1UL << 6) 
#define ACSR_ACO  (uint8_t)(1UL << 5) 
#define ACSR_ACI  (uint8_t)(1UL << 4) 
#define ACSR_ACIE  (uint8_t)(1UL << 3) 
#define ACSR_ACIC  (uint8_t)(1UL << 2) 
#define ACSR_ACIS1  (uint8_t)(1UL << 1) 
#define ACSR_ACIS0  (uint8_t)(1UL << 0) 
#define SPDR_SPI   (uint8_t)( 1UL << 7) 
#define SPSR_SPIF (uint8_t)( 1UL << 7) 
#define SPSR_WCOL (uint8_t)( 1UL << 6) 
#define SPCR_SPIE (uint8_t)( 1UL << 7) 
#define SPCR_SPE (uint8_t)( 1UL << 6) 
#define SPCR_DORD  (uint8_t)(1UL << 5) 
#define SPCR_MSTR  (uint8_t)(1UL << 4) 
#define SPCR_CPOL  (uint8_t)(1UL << 3) 
#define SPCR_CPHA  (uint8_t)(1UL << 2) 
#define SPCR_SPR1  (uint8_t)(1UL << 1) 
#define SPCR_SPR0  (uint8_t)(1UL << 0) 
#define GPIOR2_General_purpose_I_O (uint8_t)( 1UL << 7) 
#define GPIOR1_General_purpose_I_O (uint8_t)( 1UL << 7) 
#define OCR0B_Timer(uint8_t)( 1UL << 7) 
#define OCR0A_Timer (uint8_t)( 1UL << 7) 
#define TCNT0_Timer (uint8_t)( 1UL << 7) 
#define TCCR0B_FOC0A (uint8_t)( 1UL << 7) 
#define TCCR0B_FOC0B (uint8_t)( 1UL << 6) 
#define TCCR0B_WGM02  (uint8_t)(1UL << 3) 
#define TCCR0B_CS02  (uint8_t)(1UL << 2) 
#define TCCR0B_CS01  (uint8_t)(1UL << 1) 
#define TCCR0B_CS00  (uint8_t)(1UL << 0) 
#define TCCR0A_COM0A1 (uint8_t)( 1UL << 7) 
#define TCCR0A_COM0A0 (uint8_t)( 1UL << 6) 
#define TCCR0A_COM0B1  (uint8_t)(1UL << 5) 
#define TCCR0A_COM0B0  (uint8_t)(1UL << 4) 
#define TCCR0A_WGM01  (uint8_t)(1UL << 1) 
#define TCCR0A_WGM00  (uint8_t)(1UL << 0) 
#define GTCCR_TSM (uint8_t)( 1UL << 7) 
#define GTCCR_PSRASY  (uint8_t)(1UL << 1) 
#define GTCCR_PSRSYNC  (uint8_t)(1UL << 0) 
#define EEARH_EEPROM (uint8_t)( 1UL << 7) 
#define EEARL_EEPROM (uint8_t)( 1UL << 7) 
#define EEDR_EEPROM (uint8_t)( 1UL << 7) 
#define EECR_EEPM1  (uint8_t)(1UL << 5) 
#define EECR_EEPM0  (uint8_t)(1UL << 4) 
#define EECR_EERIE  (uint8_t)(1UL << 3) 
#define EECR_EEMPE  (uint8_t)(1UL << 2) 
#define EECR_EEPE  (uint8_t)(1UL << 1) 
#define EECR_EERE  (uint8_t)(1UL << 0) 
#define GPIOR0_General (uint8_t)( 1UL << 7) 
#define EIMSK_INT1  (uint8_t)(1UL << 1) 
#define EIMSK_INT0  (uint8_t)(1UL << 0) 
#define EIFR_INTF1  (uint8_t)(1UL << 1) 
#define EIFR_INTF0  (uint8_t)(1UL << 0) 
#define PCIFR_PCIF2  (uint8_t)(1UL << 2) 
#define PCIFR_PCIF1  (uint8_t)(1UL << 1) 
#define PCIFR_PCIF0  (uint8_t)(1UL << 0) 
#define TIFR2_OCF2B  (uint8_t)(1UL << 2) 
#define TIFR2_OCF2A  (uint8_t)(1UL << 1) 
#define TIFR2_TOV2  (uint8_t)(1UL << 0) 
#define TIFR1_ICF1  (uint8_t)(1UL << 5) 
#define TIFR1_OCF1B  (uint8_t)(1UL << 2) 
#define TIFR1_OCF1A  (uint8_t)(1UL << 1) 
#define TIFR1_TOV1  (uint8_t)(1UL << 0) 
#define TIFR0_OCF0B  (uint8_t)(1UL << 2) 
#define TIFR0_OCF0A  (uint8_t)(1UL << 1) 
#define TIFR0_TOV0  (uint8_t)(1UL << 0) 
#define PORTD_PORTD7 (uint8_t)( 1UL << 7) 
#define PORTD_PORTD6 (uint8_t)( 1UL << 6) 
#define PORTD_PORTD5  (uint8_t)(1UL << 5) 
#define PORTD_PORTD4  (uint8_t)(1UL << 4) 
#define PORTD_PORTD3  (uint8_t)(1UL << 3) 
#define PORTD_PORTD2  (uint8_t)(1UL << 2) 
#define PORTD_PORTD1  (uint8_t)(1UL << 1) 
#define PORTD_PORTD0  (uint8_t)(1UL << 0) 
#define DDRD_DDD7 (uint8_t)( 1UL << 7) 
#define DDRD_DDD6 (uint8_t)( 1UL << 6) 
#define DDRD_DDD5  (uint8_t)(1UL << 5) 
#define DDRD_DDD4  (uint8_t)(1UL << 4) 
#define DDRD_DDD3  (uint8_t)(1UL << 3) 
#define DDRD_DDD2  (uint8_t)(1UL << 2) 
#define DDRD_DDD1  (uint8_t)(1UL << 1) 
#define DDRD_DDD0  (uint8_t)(1UL << 0) 
#define PIND_PIND7 (uint8_t)( 1UL << 7) 
#define PIND_PIND6 (uint8_t)( 1UL << 6) 
#define PIND_PIND5  (uint8_t)(1UL << 5) 
#define PIND_PIND4  (uint8_t)(1UL << 4) 
#define PIND_PIND3  (uint8_t)(1UL << 3) 
#define PIND_PIND2  (uint8_t)(1UL << 2) 
#define PIND_PIND1  (uint8_t)(1UL << 1) 
#define PIND_PIND0  (uint8_t)(1UL << 0) 
#define PORTC_PORTC6 (uint8_t)( 1UL << 6) 
#define PORTC_PORTC5  (uint8_t)(1UL << 5) 
#define PORTC_PORTC4  (uint8_t)(1UL << 4) 
#define PORTC_PORTC3  (uint8_t)(1UL << 3) 
#define PORTC_PORTC2  (uint8_t)(1UL << 2) 
#define PORTC_PORTC1  (uint8_t)(1UL << 1) 
#define PORTC_PORTC0  (uint8_t)(1UL << 0) 
#define DDRC_DDC6 (uint8_t)( 1UL << 6) 
#define DDRC_DDC5  (uint8_t)(1UL << 5) 
#define DDRC_DDC4  (uint8_t)(1UL << 4) 
#define DDRC_DDC3  (uint8_t)(1UL << 3) 
#define DDRC_DDC2  (uint8_t)(1UL << 2) 
#define DDRC_DDC1  (uint8_t)(1UL << 1) 
#define DDRC_DDC0  (uint8_t)(1UL << 0) 
#define PINC_PINC6 (uint8_t)( 1UL << 6) 
#define PINC_PINC5  (uint8_t)(1UL << 5) 
#define PINC_PINC4  (uint8_t)(1UL << 4) 
#define PINC_PINC3  (uint8_t)(1UL << 3) 
#define PINC_PINC2  (uint8_t)(1UL << 2) 
#define PINC_PINC1  (uint8_t)(1UL << 1) 
#define PINC_PINC0  (uint8_t)(1UL << 0) 
#define PORTB_PORTB7 (uint8_t)( 1UL << 7) 
#define PORTB_PORTB6 (uint8_t)( 1UL << 6) 
#define PORTB_PORTB5  (uint8_t)(1UL << 5) 
#define PORTB_PORTB4  (uint8_t)(1UL << 4) 
#define PORTB_PORTB3  (uint8_t)(1UL << 3) 
#define PORTB_PORTB2  (uint8_t)(1UL << 2) 
#define PORTB_PORTB1  (uint8_t)(1UL << 1) 
#define PORTB_PORTB0  (uint8_t)(1UL << 0) 
#define DDRB_DDB7 (uint8_t)( 1UL << 7) 
#define DDRB_DDB6 (uint8_t)( 1UL << 6) 
#define DDRB_DDB5  (uint8_t)(1UL << 5) 
#define DDRB_DDB4  (uint8_t)(1UL << 4) 
#define DDRB_DDB3  (uint8_t)(1UL << 3) 
#define DDRB_DDB2  (uint8_t)(1UL << 2) 
#define DDRB_DDB1  (uint8_t)(1UL << 1) 
#define DDRB_DDB0  (uint8_t)(1UL << 0) 
#define PINB_PINB7 (uint8_t)( 1UL << 7) 
#define PINB_PINB6 (uint8_t)( 1UL << 6) 
#define PINB_PINB5  (uint8_t)(1UL << 5) 
#define PINB_PINB4  (uint8_t)(1UL << 4) 
#define PINB_PINB3  (uint8_t)(1UL << 3) 
#define PINB_PINB2  (uint8_t)(1UL << 2) 
#define PINB_PINB1  (uint8_t)(1UL << 1) 
#define PINB_PINB0  (uint8_t)(1UL << 0) 


#endif